server:
  port: 8083
  
spring:
  application:
    name: DCOTOR-SERVICE
  datasource:
    username: root
    password: examly
    url: jdbc:mysql://localhost:3306/hack
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8080/eureka/

  instance:
    prefer-ip-address: true

